# Generated by Django 4.2 on 2023-05-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_product_pimage_alter_product_cat_alter_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sataus',
            new_name='status',
        ),
    ]
